FROM nginx:1.25.2
COPY Certs/amrita-local.net.crt /etc/nginx/certs/amrita-local.net.crt
COPY Certs/amrita-local.net.key /etc/nginx/certs/amrita-local.net.key

COPY Certs/amrita-local.io.crt /etc/nginx/certs/amrita-local.io.crt
COPY Certs/amrita-local.io.key /etc/nginx/certs/amrita-local.io.key

COPY default.conf /etc/nginx/conf.d/default.conf
