version: "3.8"

services:
  nginx-foundation:
    image: project-chimera/nginx-amrita:0.0.3
    build:
      context: .
      dockerfile: DockerFile
    container_name: nginx-foundation
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - vol-nginx-conf-data:/etc/nginx
    networks:
      - net-amrita
      
networks:
  net-amrita:
    external: true
    name: net-amrita

volumes:
  vol-nginx-conf-data:
    driver: local
    name: vol-nginx-conf-data